name: Generate Snake

on:
  schedule: # Executa automaticamente a cada 6 horas
    - cron: "0 */6 * * *"

  workflow_dispatch: # Permite execução manual do GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: deividleal
          outputs: dist/snake.svg

      - name: Upload to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
